name: Publish

on: 
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - uses: cachix/cachix-action@v6
      with:
        name: amarrella
        signingKey: '${{ secrets.AMARRELLA_PUBLIC_SIGNING_KEY }}'
        extraPullNames: iohk
    - run: nix-build -A blog.components.exes.build-site
    - run: result/bin/build-site
    - uses: peter-evans/create-pull-request@v2
      with:
        title: Publish
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
